// <auto-generated />
using System;
using ElectionService.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectionService.Migrations
{
    [DbContext(typeof(ElectionContext))]
    [Migration("20230526091831_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectionService.Model.Bulletin", b =>
                {
                    b.Property<int>("BulletinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BulletinId"));

                    b.Property<int>("ListeId")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("BulletinId");

                    b.HasIndex("ListeId");

                    b.ToTable("Bulletins");
                });

            modelBuilder.Entity("ElectionService.Model.Candidat", b =>
                {
                    b.Property<int>("CandidatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidatId"));

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListeId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidatId");

                    b.ToTable("Candidats");
                });

            modelBuilder.Entity("ElectionService.Model.Commune", b =>
                {
                    b.Property<int>("communeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("communeId"));

                    b.Property<string>("canton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("npa")
                        .HasColumnType("int");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("communeId");

                    b.ToTable("Communes");
                });

            modelBuilder.Entity("ElectionService.Model.Election", b =>
                {
                    b.Property<int>("ElectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElectionId"));

                    b.Property<int>("CommuneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateElection")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbBulletin")
                        .HasColumnType("int");

                    b.Property<int>("NbBulletinBlanc")
                        .HasColumnType("int");

                    b.Property<int>("NbBulletinNull")
                        .HasColumnType("int");

                    b.Property<int>("NbSiege")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ElectionId");

                    b.HasIndex("CommuneId");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("ElectionService.Model.Liste", b =>
                {
                    b.Property<int>("ListeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListeId"));

                    b.Property<string>("Abreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbBulletinCompact")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("ListeId");

                    b.ToTable("Listes");
                });

            modelBuilder.Entity("ElectionService.Model.Suffrage", b =>
                {
                    b.Property<int>("suffrageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("suffrageId"));

                    b.Property<int>("nbVote")
                        .HasColumnType("int");

                    b.HasKey("suffrageId");

                    b.ToTable("Suffrages");
                });

            modelBuilder.Entity("ElectionService.Model.Bulletin", b =>
                {
                    b.HasOne("ElectionService.Model.Liste", null)
                        .WithMany("Bulletins")
                        .HasForeignKey("ListeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectionService.Model.Election", b =>
                {
                    b.HasOne("ElectionService.Model.Commune", "Commune")
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commune");
                });

            modelBuilder.Entity("ElectionService.Model.Liste", b =>
                {
                    b.Navigation("Bulletins");
                });
#pragma warning restore 612, 618
        }
    }
}
